#!/usr/bin/bash

set -x

rm -rf ../SHiELD_SRC/*
rm -rf ../SERIALBOX_BUILD/*
./CHECKOUT_code

cd Build

##### SHiELD DEBUG
#rm build_shield_nh.debug.64bit.gnu.out
#./COMPILE cleanall shield nh debug 64bit gnu serial
#./COMPILE cleanall shield nh debug 64bit intel serial
#./COMPILE cleanall shield nh debug 64bit intel noserial
#./COMPILE cleanall shield nh repro 64bit intel noserial
#./COMPILE cleanall shield nh debug 64bit gnu noserial

# Currently working on this one --- 3/16/2026
./COMPILE cleanall shield nh repro 64bit intel serial

##### SOLO DEBUG
#./COMPILE cleanall solo nh debug 64bit gnu serial

##### SOLO REPRO
#./COMPILE cleanall solo nh repro 64bit gnu serial

cd ..
set +x
